print ("Inside python: next line will throw error code 100")
exit(100)
